"""
Report Formatter for Risk Agent Analyzer

Provides professional formatting for analysis reports.
"""

import logging
from typing import List, Dict, Any
from datetime import datetime

class ReportFormatter:
    """Formats analysis reports with professional styling"""
    
    def __init__(self, config: Dict[str, Any]):
        """Initialize report formatter"""
        self.config = config
        self.logger = logging.getLogger(__name__)
        self.width = 120  # Professional report width
    
    def format_header(self, title: str, subtitle: str = "") -> List[str]:
        """Format professional report header"""
        lines = []
        lines.append("=" * self.width)
        lines.append(title.center(self.width))
        if subtitle:
            lines.append(subtitle.center(self.width))
        lines.append("=" * self.width)
        lines.append("")
        return lines
    
    def format_section_header(self, section: str, level: int = 1) -> List[str]:
        """Format section headers with appropriate styling"""
        lines = []
        
        if level == 1:
            lines.append("=" * self.width)
            lines.append(section)
            lines.append("=" * self.width)
        else:
            lines.append("-" * self.width)
            lines.append(section)
            lines.append("-" * self.width)
        
        lines.append("")
        return lines
    
    def format_key_value(self, key: str, value: str, indent: int = 0) -> str:
        """Format key-value pairs consistently"""
        spacing = " " * indent
        return f"{spacing}{key}: {value}"
    
    def format_metrics_table(self, metrics: Dict[str, Any]) -> List[str]:
        """Format metrics in a clean table format"""
        lines = []
        
        for key, value in metrics.items():
            formatted_key = key.replace('_', ' ').title()
            lines.append(self.format_key_value(formatted_key, str(value)))
        
        return lines
    
    def format_footer(self) -> List[str]:
        """Format professional report footer"""
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        lines = []
        lines.append("=" * self.width)
        lines.append("END OF REPORT - Generated by Risk Agent Analyzer")
        lines.append(f"Report Generated: {timestamp} UTC")
        lines.append("=" * self.width)
        return lines
